#!/bin/sh
set -e

files=https://raw.githubusercontent.com/pbrisbin/arch-setup/main/files/

curl_file() {
  url=$files/$1
  curl --location --silent --fail "$url"
}

install_file() {
  path=$1
  name=$(basename "$path")
  mkdir -p "$(dirname "$path")"
  curl_file "$name" >"$path"
}

echo "Running archinstall"
archinstall --config "$files/config.json" --mount-point /mnt

echo "Adding files"
install_file /mnt/etc/X11/xorg.conf.d/10-keyboard.conf
install_file /mnt/etc/acpi/handler.sh
install_file /mnt/etc/aurto/trusted-users
install_file /mnt/etc/netctl/ethernet
install_file /mnt/etc/pacman.d/hooks/mirrorupgrade.hook
install_file /mnt/etc/pacman.d/hooks/stack-completions.hook
install_file /mnt/etc/xdg/reflector/reflector.conf
install_file /mnt/home/patrick/.zshrc
install_file /mnt/home/patrick/aur-packages.csv
install_file /mnt/home/patrick/install-aur
install_file /mnt/home/patrick/install-dotfiles
install_file /mnt/root/.config/nvim/init.vim

echo "Adjusting files"
sed -i 's/^#\(Color\)/\1/' /mnt/etc/pacman.conf
sed -i 's/^#\(AutoEnable=\).*/\1=true/' /mnt/etc/bluetooth/main.conf

echo "Configuring networking"
eth0=$(ip link | sed '/^[0-9]*: \(en[^:]*\):.*$/!d; s//\1/' | head -n 1)
wan0=$(ip link | sed '/^[0-9]*: \(wl[^:]*\):.*$/!d; s//\1/' | head -n 1)

m4 -D "INTERFACE=$eth0" </mnt/etc/netctl/ethernet >"/mnt/etc/netctl/$eth0-ethernet"
rm /mnt/etc/netctl/ethernet

systemctl enable "netctl-auto@$wan0" "netctl-ifplugd@$eth0"

echo "Preparing for reboot as user"
chown patrick:patrick /mnt/home/patrick/.zshrc
chown patrick:patrick /mnt/home/patrick/*
chmod +x /mnt/home/patrick/install-*

echo
echo "Done. Have a look around, reboot when ready."
