#!/bin/sh
set -e

cut -d, -f2 ./aur-packages.csv | sort -u | sudo tee -a /etc/aurto/trusted-users
cut -d, -f3 ./aur-packages.csv | sort -u | xargs gpg --recv-keys

curl -L https://aur.archlinux.org/cgit/aur.git/snapshot/aurutils.tar.gz | tar xz
curl -L https://aur.archlinux.org/cgit/aur.git/snapshot/aurto.tar.gz | tar xz

(cd aurutils && makepkg -srci --noconfirm)
(cd aurto && makepkg -srci --noconfirm)

aurto init

cut -d, -f1 ./aur-packages.csv | xargs aurto add
cut -d, -f1 ./aur-packages.csv | xargs sudo pacman -Syu --needed --noconfirm
